### ISSUE TITLE
Feature Request: return when value changes (differs from previous invocation)

### ISSUE THREAD

**Issue by mcint** [dimo414/bkt#20]
`bkt` stores state across invocations, and can diffs easily. I suppose it's not currently diffing data, just conditionally refreshing based on time and flags.

I find myself wanting to only see new data when a source changes, and a tool that caches data seems like the right place make a change.

PRs accepted?

It's possible this feature falls outside the scope of what maintainers want to maintain.

**Comment by dimo414** [comment]
Right, it doesn't do any sort of introspection on the cached data, it simply invalidates the cache and triggers a new execution based on the configuration when it's invoked. Since it doesn't _actually_ execute the backing process unless the cache is invalidated it's not possible to use the command's output as part of the cache key.

> I find myself wanting to only see new data when a source changes

Can you share more details of your use case? You might be able to use [`watch`](https://manpages.debian.org/watch) for the purpose you're describing. With `bkt` you can potentially use a custom `--scope` which might work for your situation but it's hard to say without more specifics. I'm also working (slowly...) on #10 which would let you use file modtimes as part of the cache key in a similar fashion to scopes.

**Comment by mcint** [comment]
`watch` is good at showing updates interactively, but I don't know of nice ways to feed its output further down a shell pipeline. I want to run commands when something is new.

The proposed functionality would operate as `--force` on decision to run command, would compare for exact match with backing data, and would modify output behavior. 

---
Most recently, I have articles read to me `while true; do [ifnew] pbpaste | say; sleep .25; done`. I use shell idioms, but want to keep tightening great reusable functionality into tools. `if [[ $cur != $prev ]]; then prev=$cur; [edge-triggered action]; fi`. This project also started as a shell script?

I use urlwatch, and I'd like to decompose that into shell parts. Until 2015, it used a format of 1 shell command-pipeline per line. It watches and diffs: direct HTTP responses ("url"), shell command outputs, and headless browser responses; and applies normalizing filters before diffing. This use case really isn't appropriate for an extension of bkt. URLs can be queried with ETag or If-Modified-Since / Last-Modified-Time.

**Comment by dimo414** [comment]
Ok I think I follow you. `bkt` won't support checking a webpage's last-modified-time natively, but you could do it yourself using `--scope`, something like (pseudocode):

```
bkt --scope="$(get_last_modified "$URL")" --ttl=1h -- do_something_expensive "$URL"
```

I don't know that this is really particularly clearer or more elegant than what you're already doing.

**Comment by dimo414** [comment]
I'm going to close this FR since `bkt` does not support invalidating the cache on the basis of the command's output (since, again, the backing command is not executed at all if a cached invocation exists). Please feel free to file other feature requests though!
