### ISSUE TITLE
cannot build rev 0.5.4 without updating cargo.lock

### ISSUE THREAD

**Issue by MangoIV** [dimo414/bkt#23]
the cargo.lock update to 0.5.4 was not included in the 0.5.4 release

**Comment by dimo414** [comment]
Ah that was sloppy :) Can you clarify in what circumstance this is an issue? I just tried both depending on 0.5.4 from a library and installing 0.5.4 via `cargo install` and neither seem to have a problem. I just want to understand the severity.

**Comment by MangoIV** [comment]
See

**Comment by MangoIV** [comment]
I'm trying to package this for nixpkgs and normally a `ref` is specified for the package version but cargo will try to update the `cargo.lock` when building for `ref=0.5.4` and the build will fail due to a hash mismatch

**Comment by dimo414** [comment]
Gotcha, and thanks for contributing a NixOS package! Your workaround makes sense to me, or if you prefer you could start with 0.5.2 since both 0.5.3 and 0.5.4 were just config changes for the Debian package. I can also cut a 0.5.5 if you're unable to proceed, but I'd lean towards one of these workarounds if they make sense to you.

**Comment by dimo414** [comment]
0.6.0 is now out, so I'm going to close this. Please let me know if you're still having difficulty!
