### ISSUE TITLE
Executable missing

### ISSUE THREAD

**Issue by alexmyczko** [dimo414/bkt#37]
So when I try to run a script in the current directory

```
PATH=.:$PATH bkt --ttl 24h -- FHQ
```

also can't run

```
bkt --ttl 24h -- ./FHQ
```

I get

```
thread 'main' panicked at 'Executable missing', /usr/share/cargo/registry/bkt-0.6.1/src/lib.rs:1065:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

however

```
PATH=.:$PATH FHQ
```

works

SHELL=/bin/zsh

**Comment by dimo414** [comment]
The [line in question](https://github.com/dimo414/bkt/blob/6c1fb9a39ebe5675bf2af2bc661b216b84661a00/src/lib.rs#L1065C15-L1065C15) indicates the `Command` is malformed (namely, it lacks a 0th argument). Unfortunately that line is hit while handling a different error, which appears to be obfuscated by the `Executable missing` issue.

Are you able to share an MCVE I can use to reproduce this? My guess is there's something else going on since you can reproduce it even without tweaking the `PATH`.

**Comment by alexmyczko** [comment]
take any script that just runs echo foo. make sure it is in same directory and not PATH. that would be the MCVE.  here is an example:

https://github.com/alexmyczko/fnt/blob/main/fnt

download and chmod +x

**Comment by dimo414** [comment]
I'm afraid that isn't sufficient to reproduce what you're seeing, there is something else going on with your environment but I don't know what it would be.

```
$ cd $(mktemp -d)

$ printf '%s\n' '#!/bin/bash' 'echo foo' > foo.sh

$ chmod +x foo.sh

$ ./foo.sh
foo

$ bkt -- ./foo.sh
foo

$ PATH=.:$PATH bkt -- foo.sh
foo
```

**Comment by dimo414** [comment]
I just fixed the error handling to avoid the "Executable missing" error, can you try one of [these binaries](https://github.com/dimo414/bkt/actions/runs/5427941890) and see what it reports?

**Comment by dimo414** [comment]
Is it possible your script is missing the [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) line? [This post](https://ostechnix.com/fix-exec-format-error-when-running-scripts-with-run-parts-command/) suggests that could be the culprit.
